import HomePage from "@/app/_pages/home/HomePage";

export const metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
}

export default function Home() {

  return (
      <div className="w-full h-auto">
        <HomePage />
      </div>
  );
}
